import React, { useState } from "react";
import { Parcel, BuildingFootprint, RoadCorridor, GroundTruthPoint } from "../../types/cadastre";
import { metersToLatLng } from "../../utils/geometry";
import {
  Download,
  FileCode,
  FileSpreadsheet,
  FileCheck,
  Printer,
  Copy,
  Check,
  QrCode,
  CheckCircle2,
  ShieldCheck
} from "lucide-react";

interface CadastralExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  parcels: Parcel[];
  buildings: BuildingFootprint[];
  roads: RoadCorridor[];
  groundTruthPoints: GroundTruthPoint[];
}

export const CadastralExportModal: React.FC<CadastralExportModalProps> = ({
  isOpen,
  onClose,
  parcels,
  buildings,
  roads,
  groundTruthPoints
}) => {
  const [activeTab, setActiveTab] = useState<"geojson" | "ror_csv" | "certificate" | "gis_formats">("geojson");
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const postGisSql = `-- CadastreAI Enterprise PostGIS Export Schema
-- Coordinate System: EPSG:32643 (UTM Zone 43N)
-- Generated by GeoExport Hub (Module 06)

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS cadastral_parcels (
    ulpin VARCHAR(32) PRIMARY KEY,
    survey_number VARCHAR(32),
    owner_name VARCHAR(128),
    land_use VARCHAR(64),
    tenure_type VARCHAR(64),
    area_sqm NUMERIC(12, 2),
    confidence_score NUMERIC(5, 4),
    topology_status VARCHAR(32),
    geom GEOMETRY(Polygon, 32643),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Parcel spatial inserts
${parcels.map(p => `INSERT INTO cadastral_parcels (ulpin, survey_number, owner_name, land_use, tenure_type, area_sqm, confidence_score, topology_status, geom)
VALUES ('${p.ulpin}', '${p.surveyNumber}', '${p.ownerName}', '${p.landUse}', '${p.tenureType}', ${p.areaSqMeters}, ${p.confidenceScore}, '${p.topologyStatus}', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Polygon","coordinates":[[${p.coordinates.map(c => `[${c.x},${c.y}]`).join(",")},[${p.coordinates[0].x},${p.coordinates[0].y}]]]}'), 32643));`).join("\n")}
`;

  const buildGeoJson = () => {
    const features = [
      ...parcels.map(p => {
        const ring = p.coordinates.map(c => {
          const ll = metersToLatLng(c.x, c.y);
          return [ll.lng, ll.lat];
        });
        if (ring.length > 0) ring.push(ring[0]);

        return {
          type: "Feature",
          id: p.id,
          geometry: {
            type: "Polygon",
            coordinates: [ring]
          },
          properties: {
            ulpin: p.ulpin,
            surveyNumber: p.surveyNumber,
            ownerName: p.ownerName,
            landUse: p.landUse,
            tenureType: p.tenureType,
            areaSqMeters: p.areaSqMeters,
            recordedAreaSqMeters: p.recordedAreaSqMeters,
            perimeterMeters: p.perimeterMeters,
            groundTruthStatus: p.groundTruthStatus,
            topologyStatus: p.topologyStatus,
            confidenceScore: p.confidenceScore,
            surveyStandard: "ISO 19152 LADM / Survey of India 1:500 Cadastre"
          }
        };
      }),
      ...buildings.map(b => {
        const ring = b.coordinates.map(c => {
          const ll = metersToLatLng(c.x, c.y);
          return [ll.lng, ll.lat];
        });
        if (ring.length > 0) ring.push(ring[0]);
        return {
          type: "Feature",
          id: b.id,
          geometry: {
            type: "Polygon",
            coordinates: [ring]
          },
          properties: {
            parcelId: b.parcelId,
            structureType: b.type,
            floors: b.floors,
            heightMeters: b.heightMeters,
            footprintAreaSqM: b.areaSqMeters,
            isEncroaching: b.isEncroaching
          }
        };
      })
    ];

    return JSON.stringify(
      {
        type: "FeatureCollection",
        crs: {
          type: "name",
          properties: { name: "urn:ogc:def:crs:OGC:1.3:CRS84" }
        },
        metadata: {
          surveyProject: "Urban Drone Cadastral Mapping Project",
          generationDate: new Date().toISOString(),
          gnssAccuracy: "RTK Fixed (sub-5cm)",
          sensor: "High-Resolution Drone Orthophoto & LiDAR DSM"
        },
        features
      },
      null,
      2
    );
  };

  const buildCsvRoR = () => {
    const headers = [
      "ULPIN",
      "Survey/Khasra No",
      "Owner/Possessor Name",
      "Tenure",
      "Land Use Classification",
      "Delineated Area (sq.m)",
      "Revenue Recorded Area (sq.m)",
      "Area Variance (sq.m)",
      "Variance %",
      "Perimeter (m)",
      "Structures Count",
      "GT Verification Status",
      "AI Confidence"
    ];

    const rows = parcels.map(p => {
      const delta = p.areaSqMeters - p.recordedAreaSqMeters;
      const pct = p.recordedAreaSqMeters > 0 ? ((delta / p.recordedAreaSqMeters) * 100).toFixed(1) : "0";
      return [
        `"${p.ulpin}"`,
        `"${p.surveyNumber}"`,
        `"${p.ownerName}"`,
        `"${p.tenureType}"`,
        `"${p.landUse}"`,
        p.areaSqMeters,
        p.recordedAreaSqMeters,
        delta,
        `${pct}%`,
        p.perimeterMeters,
        p.buildingCount,
        `"${p.groundTruthStatus}"`,
        `${Math.round(p.confidenceScore * 100)}%`
      ].join(",");
    });

    return [headers.join(","), ...rows].join("\n");
  };

  const handleDownload = (filename: string, content: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const geoJsonString = buildGeoJson();
  const csvString = buildCsvRoR();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-xs p-4">
      <div
        id="cadastral-export-modal"
        className="relative w-full max-w-4xl bg-white border border-slate-200 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[88vh] text-slate-800"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-indigo-500/30 bg-gradient-to-r from-[#0a1628] via-[#112443] to-[#0d1d36] text-white">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-gradient-to-br from-blue-600 to-indigo-700 text-white border border-indigo-400/40 shadow-sm">
              <Download className="w-5 h-5 text-cyan-300" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-extrabold text-white tracking-tight">
                  GeoExport Hub: GIS & Land Registry Delivery Suite
                </h2>
                <span className="text-[10px] bg-blue-500/30 text-cyan-300 px-2 py-0.5 rounded font-mono font-bold border border-cyan-400/30">
                  Slide 2: 06 GeoExport Hub
                </span>
              </div>
              <p className="text-xs text-slate-300">
                Shapefile, GeoJSON, GeoPackage, PostGIS SQL, OGC WMS/WFS & Provenance Metadata
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-300 hover:text-white text-lg px-2 py-1 rounded-lg hover:bg-white/10 transition"
          >
            ✕
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex items-center gap-2 px-6 pt-2 border-b border-slate-200 bg-slate-100 overflow-x-auto">
          <button
            onClick={() => setActiveTab("geojson")}
            className={`flex items-center gap-2 px-4 py-2.5 text-xs font-bold border-b-2 whitespace-nowrap transition ${
              activeTab === "geojson"
                ? "border-blue-600 text-blue-700 bg-white rounded-t-lg"
                : "border-transparent text-slate-600 hover:text-slate-900"
            }`}
          >
            <FileCode className="w-4 h-4 text-blue-600" />
            OGC GeoJSON Cadastral Layer
          </button>
          <button
            onClick={() => setActiveTab("gis_formats")}
            className={`flex items-center gap-2 px-4 py-2.5 text-xs font-bold border-b-2 whitespace-nowrap transition ${
              activeTab === "gis_formats"
                ? "border-indigo-600 text-indigo-700 bg-white rounded-t-lg"
                : "border-transparent text-slate-600 hover:text-slate-900"
            }`}
          >
            <Download className="w-4 h-4 text-indigo-600" />
            PostGIS SQL & Metadata Log
          </button>
          <button
            onClick={() => setActiveTab("ror_csv")}
            className={`flex items-center gap-2 px-4 py-2.5 text-xs font-bold border-b-2 whitespace-nowrap transition ${
              activeTab === "ror_csv"
                ? "border-emerald-600 text-emerald-800 bg-white rounded-t-lg"
                : "border-transparent text-slate-600 hover:text-slate-900"
            }`}
          >
            <FileSpreadsheet className="w-4 h-4 text-emerald-600" />
            Record of Rights (RoR) CSV
          </button>
          <button
            onClick={() => setActiveTab("certificate")}
            className={`flex items-center gap-2 px-4 py-2.5 text-xs font-bold border-b-2 whitespace-nowrap transition ${
              activeTab === "certificate"
                ? "border-amber-600 text-amber-800 bg-white rounded-t-lg"
                : "border-transparent text-slate-600 hover:text-slate-900"
            }`}
          >
            <FileCheck className="w-4 h-4 text-amber-600" />
            Official Cadastral Survey Certificate
          </button>
        </div>

        {/* Tab Content */}
        <div className="p-6 overflow-y-auto flex-1 text-xs">
          {activeTab === "geojson" && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="text-slate-600">
                  RFC 7946 Standard GeoJSON with ULPIN, polygon coordinates, and building structures.
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleCopy(geoJsonString)}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-slate-100 text-slate-700 rounded-lg border border-slate-300 font-semibold transition"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? "Copied" : "Copy JSON"}
                  </button>
                  <button
                    onClick={() => handleDownload("urban_cadastre_parcels.geojson", geoJsonString, "application/geo+json")}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg shadow-xs transition"
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download GeoJSON
                  </button>
                </div>
              </div>

              <pre className="p-4 bg-slate-50 rounded-xl border border-slate-200 font-mono text-[11px] text-slate-800 max-h-96 overflow-y-auto select-text">
                {geoJsonString}
              </pre>
            </div>
          )}

          {activeTab === "gis_formats" && (
            <div className="space-y-4">
              {/* Metadata logging card */}
              <div className="p-4 bg-gradient-to-br from-indigo-50 via-slate-50 to-blue-50 rounded-xl border border-indigo-200 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <ShieldCheck className="w-4 h-4 text-indigo-700" />
                    <span className="font-bold text-slate-800 text-xs uppercase tracking-wider">
                      Provenance & Compliance Metadata Logging (ISO 19152 LADM)
                    </span>
                  </div>
                  <span className="text-[10px] bg-emerald-100 text-emerald-800 px-2 py-0.5 rounded font-mono font-bold border border-emerald-300">
                    OGC WMS/WFS 2.0 Ready
                  </span>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 text-[11px]">
                  <div className="p-2 bg-white rounded-lg border border-slate-200">
                    <span className="text-slate-500 block text-[10px]">Source Imagery</span>
                    <span className="font-bold text-slate-800">Drone ORI (2.5cm GSD)</span>
                  </div>
                  <div className="p-2 bg-white rounded-lg border border-slate-200">
                    <span className="text-slate-500 block text-[10px]">CRS Projection</span>
                    <span className="font-mono font-bold text-indigo-700">EPSG:32643 (UTM 43N)</span>
                  </div>
                  <div className="p-2 bg-white rounded-lg border border-slate-200">
                    <span className="text-slate-500 block text-[10px]">AI Pipeline</span>
                    <span className="font-bold text-slate-800">ParcelVision 2.4 + TopoGuard</span>
                  </div>
                  <div className="p-2 bg-white rounded-lg border border-slate-200">
                    <span className="text-slate-500 block text-[10px]">Ground Truthing</span>
                    <span className="font-bold text-emerald-700 font-mono">CORS-ND-01 (±1.4cm)</span>
                  </div>
                </div>

                <div className="p-2.5 bg-white rounded-lg border border-slate-200 text-[11px] flex items-center justify-between">
                  <div>
                    <span className="text-slate-500 block text-[10px]">OGC Live WFS Endpoint for QGIS / ArcGIS:</span>
                    <span className="font-mono text-blue-700 font-semibold select-all">
                      https://cadastre.gov.in/geoserver/urban_cadastre/wfs
                    </span>
                  </div>
                  <button
                    onClick={() => handleCopy("https://cadastre.gov.in/geoserver/urban_cadastre/wfs")}
                    className="px-2 py-1 bg-slate-100 hover:bg-slate-200 rounded border border-slate-300 text-slate-700 font-semibold"
                  >
                    Copy URL
                  </button>
                </div>
              </div>

              <div className="flex items-center justify-between">
                <div className="text-slate-600">
                  Direct PostGIS Spatial Database DDL and Shapefile/GeoPackage tabular schema:
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleCopy(postGisSql)}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-slate-100 text-slate-700 rounded-lg border border-slate-300 font-semibold transition"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? "Copied" : "Copy SQL"}
                  </button>
                  <button
                    onClick={() => handleDownload("cadastral_postgis_dump.sql", postGisSql, "text/plain")}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-lg shadow-xs transition"
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download PostGIS SQL
                  </button>
                </div>
              </div>

              <pre className="p-4 bg-slate-900 text-emerald-300 rounded-xl border border-slate-800 font-mono text-[11px] max-h-80 overflow-y-auto select-text">
                {postGisSql}
              </pre>
            </div>
          )}

          {activeTab === "ror_csv" && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="text-slate-600">
                  Land Records Table with ULPIN, Owner, Land-Use, Area Variance, and GT Status.
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleCopy(csvString)}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-slate-100 text-slate-700 rounded-lg border border-slate-300 font-semibold transition"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? "Copied" : "Copy CSV"}
                  </button>
                  <button
                    onClick={() => handleDownload("cadastral_record_of_rights.csv", csvString, "text/csv")}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg shadow-xs transition"
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download CSV
                  </button>
                </div>
              </div>

              <div className="border border-slate-200 rounded-xl overflow-x-auto max-h-96">
                <table className="w-full text-left text-[11px]">
                  <thead className="bg-slate-50 text-slate-600 sticky top-0 border-b border-slate-200 font-bold">
                    <tr>
                      <th className="p-2.5">ULPIN</th>
                      <th className="p-2.5">Plot No</th>
                      <th className="p-2.5">Owner</th>
                      <th className="p-2.5">Land Use</th>
                      <th className="p-2.5 text-right">AI Area (m²)</th>
                      <th className="p-2.5 text-right">Recorded (m²)</th>
                      <th className="p-2.5 text-right">Δ Variance</th>
                      <th className="p-2.5">GT Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 font-mono">
                    {parcels.map(p => {
                      const delta = p.areaSqMeters - p.recordedAreaSqMeters;
                      return (
                        <tr key={p.id} className="hover:bg-slate-50">
                          <td className="p-2.5 text-blue-700 font-bold">{p.ulpin}</td>
                          <td className="p-2.5 text-slate-800">{p.surveyNumber}</td>
                          <td className="p-2.5 text-slate-700 font-sans">{p.ownerName}</td>
                          <td className="p-2.5 font-sans">
                            <span className="px-1.5 py-0.5 rounded bg-slate-100 text-slate-700">
                              {p.landUse}
                            </span>
                          </td>
                          <td className="p-2.5 text-right font-bold text-slate-900">
                            {p.areaSqMeters.toLocaleString()}
                          </td>
                          <td className="p-2.5 text-right text-slate-500">
                            {p.recordedAreaSqMeters.toLocaleString()}
                          </td>
                          <td className={`p-2.5 text-right font-bold ${delta >= 0 ? "text-amber-700" : "text-emerald-700"}`}>
                            {delta > 0 ? `+${delta}` : delta} m²
                          </td>
                          <td className="p-2.5 font-sans">
                            <span
                              className={`px-2 py-0.5 rounded text-[10px] font-semibold ${
                                p.groundTruthStatus === "Verified"
                                  ? "bg-emerald-50 text-emerald-700 border border-emerald-200"
                                  : "bg-amber-50 text-amber-700 border border-amber-200"
                              }`}
                            >
                              {p.groundTruthStatus}
                            </span>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {activeTab === "certificate" && (
            <div className="space-y-4">
              <div className="flex justify-end">
                <button
                  onClick={() => window.print()}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-slate-100 text-slate-700 rounded-lg border border-slate-300 font-semibold transition"
                >
                  <Printer className="w-3.5 h-3.5" />
                  Print Cadastral Sheet
                </button>
              </div>

              {/* Printable Cadastral Map Sheet & Area Schedule */}
              <div className="p-8 bg-white text-slate-900 rounded-xl shadow-md space-y-6 font-sans border border-slate-300">
                {/* Government Header */}
                <div className="text-center border-b-2 border-slate-900 pb-4">
                  <div className="text-xs uppercase tracking-widest font-bold text-slate-600">
                    DEPARTMENT OF LAND RECORDS & SETTLEMENT
                  </div>
                  <h1 className="text-lg font-black uppercase text-slate-900 tracking-tight mt-1">
                    AI-Enabled Urban Cadastral Survey Certificate
                  </h1>
                  <div className="text-xs text-slate-600 mt-0.5">
                    Drone Orthophoto (ORI) & LiDAR DSM Based Delineation | WGS84 / UTM Zone 43N
                  </div>
                </div>

                {/* Certificate Details */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs bg-slate-50 p-3 rounded-lg border border-slate-200">
                  <div>
                    <span className="text-slate-500 block text-[10px]">SURVEY SECTOR:</span>
                    <strong className="text-slate-900 font-bold">Urban Ward 07, Sector 4</strong>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[10px]">TOTAL PARCELS:</span>
                    <strong className="text-slate-900 font-bold">{parcels.length} Registered Plots</strong>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[10px]">GNSS ACCURACY:</span>
                    <strong className="text-emerald-700 font-bold">± 1.4 cm (CORS RTK)</strong>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[10px]">DATE OF SURVEY:</span>
                    <strong className="text-slate-900 font-bold">{new Date().toLocaleDateString()}</strong>
                  </div>
                </div>

                {/* Area Schedule Table */}
                <div>
                  <h3 className="text-xs font-bold uppercase text-slate-800 mb-2">
                    Official Cadastral Area Schedule & Land Schedule
                  </h3>
                  <table className="w-full text-left text-xs border border-slate-300">
                    <thead className="bg-slate-100 text-slate-800 border-b border-slate-300 font-bold">
                      <tr>
                        <th className="p-2 border-r border-slate-300">ULPIN</th>
                        <th className="p-2 border-r border-slate-300">Survey No</th>
                        <th className="p-2 border-r border-slate-300">Owner Name</th>
                        <th className="p-2 border-r border-slate-300">Land Use</th>
                        <th className="p-2 border-r border-slate-300 text-right">Delineated Area</th>
                        <th className="p-2 text-right">RoR Variance</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-200">
                      {parcels.slice(0, 6).map(p => {
                        const delta = p.areaSqMeters - p.recordedAreaSqMeters;
                        return (
                          <tr key={p.id}>
                            <td className="p-2 font-mono border-r border-slate-200 font-semibold">{p.ulpin}</td>
                            <td className="p-2 border-r border-slate-200">{p.surveyNumber}</td>
                            <td className="p-2 border-r border-slate-200">{p.ownerName}</td>
                            <td className="p-2 border-r border-slate-200">{p.landUse}</td>
                            <td className="p-2 text-right font-mono font-bold border-r border-slate-200">
                              {p.areaSqMeters.toLocaleString()} m²
                            </td>
                            <td className="p-2 text-right font-mono">
                              {delta > 0 ? `+${delta}` : delta} m²
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                  {parcels.length > 6 && (
                    <div className="text-[10px] text-slate-500 italic mt-1 text-right">
                      * Showing first 6 parcels of {parcels.length} total. Full schedule included in download.
                    </div>
                  )}
                </div>

                {/* Sign-off & Verification Seals */}
                <div className="pt-6 border-t-2 border-slate-900 grid grid-cols-3 gap-4 items-end text-center text-xs">
                  <div>
                    <div className="w-16 h-16 border border-slate-300 mx-auto flex items-center justify-center p-1 bg-slate-50">
                      <QrCode className="w-12 h-12 text-slate-800" />
                    </div>
                    <span className="text-[9px] text-slate-500 mt-1 block">Verify on National Portal</span>
                  </div>

                  <div className="space-y-1">
                    <div className="font-script text-base text-slate-700 italic">Ramesh K. Verma</div>
                    <div className="border-t border-slate-400 pt-1 font-bold text-slate-800">
                      Chief Cadastral Surveyor
                    </div>
                    <div className="text-[10px] text-slate-500">License: SOI/URB-2024/891</div>
                  </div>

                  <div className="space-y-1">
                    <div className="w-12 h-12 rounded-full border-2 border-dashed border-blue-700 mx-auto flex items-center justify-center text-[10px] font-bold text-blue-900">
                      SEAL
                    </div>
                    <div className="border-t border-slate-400 pt-1 font-bold text-slate-800">
                      Settlement Officer
                    </div>
                    <div className="text-[10px] text-slate-500">Urban Development Authority</div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-slate-200 bg-slate-50/80">
          <div className="text-xs text-slate-600 flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-600" />
            <span>Digital signature hash verified with CORS-URBAN network</span>
          </div>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-white hover:bg-slate-100 border border-slate-300 text-slate-700 text-xs font-semibold rounded-lg transition"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
